spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pzhdb
    username: root
    password:
    #url: jdbc:mysql://112.74.209.184:3306/pizhoudb?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    #username: doc580
    #password: doc580!#$543@1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sq580.pzh580.persistence.auto.model

pagehelper:
helperDialect: mysql
reasonable: true
supportMethodsArguments: true
params: count=countSql
server:
  port: 9020

# openApi的配置-begin
openapi:
  passwd: MGJmOTI4ZDZmYzM0MTM0YjE0ZDcxNjJjYTY5Y2Q5MThiYjE0MmQwZWVhNmRhNzVjODQxODUxZDZjY2I4ZDM4Ng==
  appkey: sq580J4Z79Z474IES
  account: pizhoushiyunheshequweishengfuwuzhongxin
  url: http://open.sq580.com
  secretkey: 9AFB3UH2II6D0Q16
  taskCorn: 0/30 * * * * ?

# openApi的配置-end



