spring:
  datasource:
    url: jdbc:mysql://118.89.57.43:3306/pzhdb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sq580.pzh580.persistence.auto.model

pagehelper:
helperDialect: mysql
reasonable: true
supportMethodsArguments: true
params: count=countSql
server:
  port: 9020




